version: 2.1

jobs:
  build:
    machine:
        enabled: true
        image: circleci/classic:201808-01
    environment:
      GOLANG_VERSION: 1.12.10
      NOTARY_VERSION: 0.6.1
      GOPATH: /home/circleci/go
      GO111MODULE: "on"
    working_directory: /home/circleci/go/src/github.com/patoarvizu/vault-agent-auto-inject-webhook
    steps:
      - checkout
      - restore_cache:
          keys:
            - vault-agent-auto-inject-webhook-golang-cache-{{ checksum "go.sum" }}
      - run:
          name: Install golang
          command: |
            sudo rm -rf /usr/local/go
            curl -Lo go.linux-amd64.tar.gz "https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"
            sudo tar -C /usr/local -xzf go.linux-amd64.tar.gz
            mkdir -p ${HOME}/go/bin
            echo 'export PATH="$GOPATH/bin:$PATH"' >> "${BASH_ENV}"
      - run:
          name: Install notary
          command: |
            curl -L https://github.com/theupdateframework/notary/releases/download/v${NOTARY_VERSION}/notary-Linux-amd64 -o notary
            chmod +x notary
            sudo mv notary /usr/local/bin
      - run:
          name: Build webhook
          command: |
            docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_ACCESS_TOKEN
            echo $ENCODED_NOTARY_ROLE_KEY | base64 -d > ${HOME}/vault-agent-auto-inject-webhook-circleci.key
            export NOTARY_DELEGATION_PASSPHRASE=$NOTARY_ROLE_PASSPHRASE
            notary -s https://notary.docker.io -d ~/.docker/trust key import ${HOME}/vault-agent-auto-inject-webhook-circleci.key --role vault-agent-auto-inject-webhook-circleci
            export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$NOTARY_DELEGATION_PASSPHRASE
            go mod vendor
            DOCKER_BUILD_ARGS="--build-arg GIT_COMMIT=$CIRCLE_SHA1 --build-arg GIT_TAG=$CIRCLE_TAG --build-arg COMMIT_TIMESTAMP=$(git log -1 --format=%at) --build-arg AUTHOR_EMAIL=$(git log -1 --format=%ae) --build-arg SIGNATURE_KEY=$(git log -1 --format=%GK)"
            docker build $DOCKER_BUILD_ARGS -t patoarvizu/vault-agent-auto-inject-webhook:$CIRCLE_SHA1 .
            export DOCKER_CONTENT_TRUST=1
            VERSION=${CIRCLE_TAG:-latest}
            docker tag patoarvizu/vault-agent-auto-inject-webhook:$CIRCLE_SHA1 patoarvizu/vault-agent-auto-inject-webhook:latest
            docker tag patoarvizu/vault-agent-auto-inject-webhook:$CIRCLE_SHA1 patoarvizu/vault-agent-auto-inject-webhook:$VERSION
            docker push patoarvizu/vault-agent-auto-inject-webhook:$CIRCLE_SHA1
            docker push patoarvizu/vault-agent-auto-inject-webhook:$VERSION
            docker push patoarvizu/vault-agent-auto-inject-webhook:latest
      - save_cache:
          key: vault-agent-auto-inject-webhook-golang-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod/cache

workflows:
  version: 2
  build-webhook:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+.\d+$/