apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-webhook
spec:
  {{- if not .Values.hpa.enable }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: vault-agent-webhook
  template:
    metadata:
      labels:
        app: vault-agent-webhook
    spec:
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 10 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: vault-agent-webhook
        image: patoarvizu/vault-agent-auto-inject-webhook:{{ .Values.imageVersion }}
        command:
        - /vault-agent-auto-inject-webhook
        - -tls-cert-file
        - {{ .Values.tls.mountPath }}/tls.crt
        - -tls-key-file
        - {{ .Values.tls.mountPath }}/tls.key
        - -ca-cert-secret-name
        - {{ .Values.flags.caCertSecretName }}
        - -vault-image-version
        - {{ .Values.flags.vaultImageVersion }}
        - -annotation-prefix
        - {{ .Values.flags.annotationPrefix }}
        - -target-vault-address
        - {{ .Values.flags.targetVaultAddress | default (printf "https://vault.%s:8200" .Release.Namespace) }}
        - -kubernetes-auth-path
        - {{ .Values.flags.kubernetesAuthPath }}
        - -default-config-map-name
        - {{ .Values.flags.defaultConfigMapName }}
        - -cpu-request
        - {{ .Values.flags.resources.requests.cpu }}
        - -cpu-limit
        - {{ .Values.flags.resources.limits.cpu }}
        - -memory-request
        - {{ .Values.flags.resources.requests.memory }}
        - -memory-limit
        - {{ .Values.flags.resources.limits.memory }}
        {{- if .Values.flags.mountCACertSecret }}
        - -mount-ca-cert-secret
        {{- end }}
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        ports:
        - name: https
          containerPort: 4443
        - name: metrics
          containerPort: 8081
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - name: tls
          mountPath: {{ .Values.tls.mountPath }}
      volumes:
      - name: tls
        secret:
          {{- if .Values.certManager.injectSecret }}
          secretName: vault-agent-webhook
          {{- else }}
          secretName: {{ .Values.tls.secretName }}
          {{- end }}