{{- if .Values.hpa.enable }}
apiVersion: {{ .Values.hpa.apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: vault-agent-webhook
spec:
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vault-agent-webhook
  metrics: {{- toYaml .Values.hpa.metricsScalingConfiguration | nindent 2 }}
{{- end }}