{{- if .Values.podDisruptionBudget.enable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vault-agent-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: vault-agent-webhook
    vault-control-plane: "true"
spec:
  {{ toYaml .Values.podDisruptionBudget.availability }}
  selector:
    matchLabels:
      app: vault-agent-webhook
{{- end }}