apiVersion: v1
kind: Service
metadata:
  name: vault-agent-webhook
  labels:
    app: vault-agent-webhook
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: https
  selector:
    app: vault-agent-webhook